// src/Utilities/feedback.utils.js

export const FEEDBACK_TYPES = {
  Satisfied: {
    id: "Satisfied",
    label: "Satisfied",
    shortLabel: "Satisfied",
    description: "Issue was resolved effectively and meets expectations",
    color: "#34d399",
    bg: "rgba(52,211,153,0.12)",
    border: "rgba(52,211,153,0.3)",
    text: "text-emerald-400",
    badgeBg: "bg-emerald-500/15",
    badgeBorder: "border-emerald-500/30",
    iconName: "thumbs-up",
  },
  Done: {
    id: "Done",
    label: "Done",
    shortLabel: "Done",
    description: "Issue is marked done and confirmed resolved",
    color: "#38bdf8",
    bg: "rgba(56,189,248,0.12)",
    border: "rgba(56,189,248,0.3)",
    text: "text-sky-400",
    badgeBg: "bg-sky-500/15",
    badgeBorder: "border-sky-500/30",
    iconName: "check-circle",
  },
};

export const QUICK_TAGS = [
  "Fast resolution",
  "Clear communication",
  "Very helpful staff",
  "Solved on first try",
  "Everything working now",
  "Needs follow-up",
];

/**
 * Parse a raw comment string from DB into structured feedback:
 * { type: "Satisfied" | "Done", note: string, tags: string[] }
 */
export const parseFeedbackComment = (rawComment) => {
  if (!rawComment || typeof rawComment !== "string") {
    return {
      type: "Satisfied",
      note: "",
      tags: [],
    };
  }

  let text = rawComment.trim();
  let type = "Satisfied";
  const tags = [];

  // Match leading [Satisfied] or [Done]
  const typeMatch = text.match(/^\[(Satisfied|Done)\]\s*/i);
  if (typeMatch) {
    const matchedType = typeMatch[1].toLowerCase();
    type = matchedType === "done" ? "Done" : "Satisfied";
    text = text.slice(typeMatch[0].length).trim();
  } else {
    // Match Satisfied: or Done: prefix
    const prefixMatch = text.match(/^(Satisfied|Done)\s*[:-]\s*/i);
    if (prefixMatch) {
      const matchedType = prefixMatch[1].toLowerCase();
      type = matchedType === "done" ? "Done" : "Satisfied";
      text = text.slice(prefixMatch[0].length).trim();
    } else if (/^(Satisfied|Done)$/i.test(text)) {
      type = text.toLowerCase() === "done" ? "Done" : "Satisfied";
      text = "";
    }
  }

  // Extract tags in brackets like [Fast resolution] or [Tags: A, B]
  const tagsMatch = text.match(/^\[Tags:\s*([^\]]+)\]\s*/i);
  if (tagsMatch) {
    const list = tagsMatch[1].split(",").map((t) => t.trim()).filter(Boolean);
    tags.push(...list);
    text = text.slice(tagsMatch[0].length).trim();
  }

  // If default text generated by frontend, clean it up
  if (
    text === "Confirmed resolved by requester." ||
    text === "Confirmed by requester." ||
    text === "Confirmed resolved."
  ) {
    text = "";
  }

  return {
    type: FEEDBACK_TYPES[type] ? type : "Satisfied",
    note: text,
    tags,
  };
};

/**
 * Format feedback fields into a clean text comment for database storage and emails.
 * e.g. "[Satisfied] [Tags: Fast resolution] Excellent support!"
 */
export const formatFeedbackComment = (type = "Satisfied", note = "", tags = []) => {
  const cleanType = type === "Done" ? "Done" : "Satisfied";
  const cleanNote = (note || "").trim();
  const selectedTags = Array.isArray(tags) ? tags.filter(Boolean) : [];

  const parts = [`[${cleanType}]`];

  if (selectedTags.length > 0) {
    parts.push(`[Tags: ${selectedTags.join(", ")}]`);
  }

  if (cleanNote) {
    parts.push(cleanNote);
  } else {
    parts.push("Confirmed resolved by requester.");
  }

  return parts.join(" ");
};
